### ISSUE TITLE
Code of conduct link produces 404

### ISSUE THREAD

**Issue by lukaseder** [r2dbc/r2dbc.github.io#20]
At the bottom of the websites, e.g. https://r2dbc.io, there's a Code of Conduct link that points here:
https://github.com/r2dbc/r2dbc-spi/blob/main/CODE_OF_CONDUCT.adoc

This document seems to no longer exist.

**Comment by mp911de** [comment]
Thanks for reporting the issue. That's fixed with 9403cb8b28a3adb466a1f2448231d0b6df1d1b87.
